
import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import { LanguageProvider } from '../components/languageContext';
import LayoutDecider from '../components/LayoutDecider';
import { GlobalProvider } from '@/context/GlobalContext';
import { EventBusProvider } from '@/context/EventBusContext';

export const metadata: Metadata = {
  title: 'oprmatrix',
  description: 'oprmatrix Generated by Torus'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
  <GlobalProvider>
    <EventBusProvider>
      <LanguageProvider>
        <div className=''>
          <LayoutDecider 
            mode='fluid' 
            navigationStyles='vertical' 
            sidebarStyle='condensed'
            >
            <div>
              <main>{children}</main>    
            </div>      
              <ToastContainer />
            </LayoutDecider>
          </div>
      </LanguageProvider>
    </EventBusProvider>
  </GlobalProvider>
  )
}
